[build]
target = "x86_64-unknown-uefi"

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[target.x86_64-unknown-uefi]
runner = "scripts/run_qemu.sh"

[net]
git-fetch-with-cli = true
